// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoCommon.proto

package com.game.proto;

public final class ProtoCommon {
  private ProtoCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ProtoError}
   */
  public enum ProtoError
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <code>FAILED = 1;</code>
     */
    FAILED(1),
    /**
     * <code>INVALID_LOGIN_TOKEN = 2;</code>
     */
    INVALID_LOGIN_TOKEN(2),
    /**
     * <code>INVALID_GAME_TICKET = 3;</code>
     */
    INVALID_GAME_TICKET(3),
    /**
     * <code>INVALID_PARAM = 10;</code>
     */
    INVALID_PARAM(10),
    /**
     * <code>NAME_LENGTH_INVALID = 11;</code>
     */
    NAME_LENGTH_INVALID(11),
    /**
     * <code>NOTICE_LENGTH_INVALID = 12;</code>
     */
    NOTICE_LENGTH_INVALID(12),
    /**
     * <code>COST_NOT_ENOUGH = 13;</code>
     */
    COST_NOT_ENOUGH(13),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>FAILED = 1;</code>
     */
    public static final int FAILED_VALUE = 1;
    /**
     * <code>INVALID_LOGIN_TOKEN = 2;</code>
     */
    public static final int INVALID_LOGIN_TOKEN_VALUE = 2;
    /**
     * <code>INVALID_GAME_TICKET = 3;</code>
     */
    public static final int INVALID_GAME_TICKET_VALUE = 3;
    /**
     * <code>INVALID_PARAM = 10;</code>
     */
    public static final int INVALID_PARAM_VALUE = 10;
    /**
     * <code>NAME_LENGTH_INVALID = 11;</code>
     */
    public static final int NAME_LENGTH_INVALID_VALUE = 11;
    /**
     * <code>NOTICE_LENGTH_INVALID = 12;</code>
     */
    public static final int NOTICE_LENGTH_INVALID_VALUE = 12;
    /**
     * <code>COST_NOT_ENOUGH = 13;</code>
     */
    public static final int COST_NOT_ENOUGH_VALUE = 13;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProtoError valueOf(int value) {
      return forNumber(value);
    }

    public static ProtoError forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return FAILED;
        case 2: return INVALID_LOGIN_TOKEN;
        case 3: return INVALID_GAME_TICKET;
        case 10: return INVALID_PARAM;
        case 11: return NAME_LENGTH_INVALID;
        case 12: return NOTICE_LENGTH_INVALID;
        case 13: return COST_NOT_ENOUGH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtoError>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtoError> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtoError>() {
            public ProtoError findValueByNumber(int number) {
              return ProtoError.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.proto.ProtoCommon.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtoError[] VALUES = values();

    public static ProtoError valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtoError(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoError)
  }

  /**
   * Protobuf enum {@code ProtoCode}
   */
  public enum ProtoCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INVALID = 0;</code>
     */
    INVALID(0),
    /**
     * <code>ERROR_MESSAGE = 1;</code>
     */
    ERROR_MESSAGE(1),
    /**
     * <code>HEART_BEAT_REQUEST = 2;</code>
     */
    HEART_BEAT_REQUEST(2),
    /**
     * <code>HEART_BEAT_RESPONSE = 3;</code>
     */
    HEART_BEAT_RESPONSE(3),
    /**
     * <code>LOGIN_REQUEST = 10;</code>
     */
    LOGIN_REQUEST(10),
    /**
     * <code>LOGIN_RESPONSE = 11;</code>
     */
    LOGIN_RESPONSE(11),
    /**
     * <code>LOGOUT_REQUEST = 12;</code>
     */
    LOGOUT_REQUEST(12),
    /**
     * <code>LOGOUT_RESPONSE = 13;</code>
     */
    LOGOUT_RESPONSE(13),
    /**
     * <code>KICK_OUT_REQUEST = 14;</code>
     */
    KICK_OUT_REQUEST(14),
    /**
     * <code>KICK_OUT_RESPONSE = 15;</code>
     */
    KICK_OUT_RESPONSE(15),
    /**
     * <code>LOGIN_INIT_REQUEST = 20;</code>
     */
    LOGIN_INIT_REQUEST(20),
    /**
     * <code>PERFORMANCE_TEST_REQ = 21;</code>
     */
    PERFORMANCE_TEST_REQ(21),
    /**
     * <code>PERFORMANCE_TEST_RES = 22;</code>
     */
    PERFORMANCE_TEST_RES(22),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>INVALID = 0;</code>
     */
    public static final int INVALID_VALUE = 0;
    /**
     * <code>ERROR_MESSAGE = 1;</code>
     */
    public static final int ERROR_MESSAGE_VALUE = 1;
    /**
     * <code>HEART_BEAT_REQUEST = 2;</code>
     */
    public static final int HEART_BEAT_REQUEST_VALUE = 2;
    /**
     * <code>HEART_BEAT_RESPONSE = 3;</code>
     */
    public static final int HEART_BEAT_RESPONSE_VALUE = 3;
    /**
     * <code>LOGIN_REQUEST = 10;</code>
     */
    public static final int LOGIN_REQUEST_VALUE = 10;
    /**
     * <code>LOGIN_RESPONSE = 11;</code>
     */
    public static final int LOGIN_RESPONSE_VALUE = 11;
    /**
     * <code>LOGOUT_REQUEST = 12;</code>
     */
    public static final int LOGOUT_REQUEST_VALUE = 12;
    /**
     * <code>LOGOUT_RESPONSE = 13;</code>
     */
    public static final int LOGOUT_RESPONSE_VALUE = 13;
    /**
     * <code>KICK_OUT_REQUEST = 14;</code>
     */
    public static final int KICK_OUT_REQUEST_VALUE = 14;
    /**
     * <code>KICK_OUT_RESPONSE = 15;</code>
     */
    public static final int KICK_OUT_RESPONSE_VALUE = 15;
    /**
     * <code>LOGIN_INIT_REQUEST = 20;</code>
     */
    public static final int LOGIN_INIT_REQUEST_VALUE = 20;
    /**
     * <code>PERFORMANCE_TEST_REQ = 21;</code>
     */
    public static final int PERFORMANCE_TEST_REQ_VALUE = 21;
    /**
     * <code>PERFORMANCE_TEST_RES = 22;</code>
     */
    public static final int PERFORMANCE_TEST_RES_VALUE = 22;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProtoCode valueOf(int value) {
      return forNumber(value);
    }

    public static ProtoCode forNumber(int value) {
      switch (value) {
        case 0: return INVALID;
        case 1: return ERROR_MESSAGE;
        case 2: return HEART_BEAT_REQUEST;
        case 3: return HEART_BEAT_RESPONSE;
        case 10: return LOGIN_REQUEST;
        case 11: return LOGIN_RESPONSE;
        case 12: return LOGOUT_REQUEST;
        case 13: return LOGOUT_RESPONSE;
        case 14: return KICK_OUT_REQUEST;
        case 15: return KICK_OUT_RESPONSE;
        case 20: return LOGIN_INIT_REQUEST;
        case 21: return PERFORMANCE_TEST_REQ;
        case 22: return PERFORMANCE_TEST_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtoCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtoCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtoCode>() {
            public ProtoCode findValueByNumber(int number) {
              return ProtoCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.proto.ProtoCommon.getDescriptor().getEnumTypes().get(1);
    }

    private static final ProtoCode[] VALUES = values();

    public static ProtoCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtoCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoCode)
  }

  public interface ErrorMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ErrorMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>int32 errCode = 1;</code>
     */
    int getErrCode();
  }
  /**
   * Protobuf type {@code ErrorMessage}
   */
  public  static final class ErrorMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ErrorMessage)
      ErrorMessageOrBuilder {
    // Use ErrorMessage.newBuilder() to construct.
    private ErrorMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorMessage() {
      errCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ErrorMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              errCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.ProtoCommon.internal_static_ErrorMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.ProtoCommon.internal_static_ErrorMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.ProtoCommon.ErrorMessage.class, com.game.proto.ProtoCommon.ErrorMessage.Builder.class);
    }

    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errCode_;
    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>int32 errCode = 1;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errCode_ != 0) {
        output.writeInt32(1, errCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.proto.ProtoCommon.ErrorMessage)) {
        return super.equals(obj);
      }
      com.game.proto.ProtoCommon.ErrorMessage other = (com.game.proto.ProtoCommon.ErrorMessage) obj;

      boolean result = true;
      result = result && (getErrCode()
          == other.getErrCode());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.proto.ProtoCommon.ErrorMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.ProtoCommon.ErrorMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.ErrorMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.ProtoCommon.ErrorMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.ErrorMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.proto.ProtoCommon.ErrorMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.ErrorMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.proto.ProtoCommon.ErrorMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.ErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.proto.ProtoCommon.ErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.proto.ProtoCommon.ErrorMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ErrorMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ErrorMessage)
        com.game.proto.ProtoCommon.ErrorMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.proto.ProtoCommon.internal_static_ErrorMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.proto.ProtoCommon.internal_static_ErrorMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.proto.ProtoCommon.ErrorMessage.class, com.game.proto.ProtoCommon.ErrorMessage.Builder.class);
      }

      // Construct using com.game.proto.ProtoCommon.ErrorMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.proto.ProtoCommon.internal_static_ErrorMessage_descriptor;
      }

      public com.game.proto.ProtoCommon.ErrorMessage getDefaultInstanceForType() {
        return com.game.proto.ProtoCommon.ErrorMessage.getDefaultInstance();
      }

      public com.game.proto.ProtoCommon.ErrorMessage build() {
        com.game.proto.ProtoCommon.ErrorMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.proto.ProtoCommon.ErrorMessage buildPartial() {
        com.game.proto.ProtoCommon.ErrorMessage result = new com.game.proto.ProtoCommon.ErrorMessage(this);
        result.errCode_ = errCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.proto.ProtoCommon.ErrorMessage) {
          return mergeFrom((com.game.proto.ProtoCommon.ErrorMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.proto.ProtoCommon.ErrorMessage other) {
        if (other == com.game.proto.ProtoCommon.ErrorMessage.getDefaultInstance()) return this;
        if (other.getErrCode() != 0) {
          setErrCode(other.getErrCode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.proto.ProtoCommon.ErrorMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.proto.ProtoCommon.ErrorMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errCode_ ;
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>int32 errCode = 1;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>int32 errCode = 1;</code>
       */
      public Builder setErrCode(int value) {
        
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>int32 errCode = 1;</code>
       */
      public Builder clearErrCode() {
        
        errCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ErrorMessage)
    }

    // @@protoc_insertion_point(class_scope:ErrorMessage)
    private static final com.game.proto.ProtoCommon.ErrorMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.proto.ProtoCommon.ErrorMessage();
    }

    public static com.game.proto.ProtoCommon.ErrorMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorMessage>
        PARSER = new com.google.protobuf.AbstractParser<ErrorMessage>() {
      public ErrorMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ErrorMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorMessage> getParserForType() {
      return PARSER;
    }

    public com.game.proto.ProtoCommon.ErrorMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 客户端时间
     * </pre>
     *
     * <code>int64 clientTime = 1;</code>
     */
    long getClientTime();
  }
  /**
   * Protobuf type {@code HeartBeatRequest}
   */
  public  static final class HeartBeatRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeatRequest)
      HeartBeatRequestOrBuilder {
    // Use HeartBeatRequest.newBuilder() to construct.
    private HeartBeatRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatRequest() {
      clientTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HeartBeatRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              clientTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.ProtoCommon.internal_static_HeartBeatRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.ProtoCommon.internal_static_HeartBeatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.ProtoCommon.HeartBeatRequest.class, com.game.proto.ProtoCommon.HeartBeatRequest.Builder.class);
    }

    public static final int CLIENTTIME_FIELD_NUMBER = 1;
    private long clientTime_;
    /**
     * <pre>
     * 客户端时间
     * </pre>
     *
     * <code>int64 clientTime = 1;</code>
     */
    public long getClientTime() {
      return clientTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientTime_ != 0L) {
        output.writeInt64(1, clientTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.proto.ProtoCommon.HeartBeatRequest)) {
        return super.equals(obj);
      }
      com.game.proto.ProtoCommon.HeartBeatRequest other = (com.game.proto.ProtoCommon.HeartBeatRequest) obj;

      boolean result = true;
      result = result && (getClientTime()
          == other.getClientTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getClientTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.proto.ProtoCommon.HeartBeatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.ProtoCommon.HeartBeatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.HeartBeatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.ProtoCommon.HeartBeatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.HeartBeatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.proto.ProtoCommon.HeartBeatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.HeartBeatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.proto.ProtoCommon.HeartBeatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.HeartBeatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.proto.ProtoCommon.HeartBeatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.proto.ProtoCommon.HeartBeatRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatRequest)
        com.game.proto.ProtoCommon.HeartBeatRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.proto.ProtoCommon.internal_static_HeartBeatRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.proto.ProtoCommon.internal_static_HeartBeatRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.proto.ProtoCommon.HeartBeatRequest.class, com.game.proto.ProtoCommon.HeartBeatRequest.Builder.class);
      }

      // Construct using com.game.proto.ProtoCommon.HeartBeatRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.proto.ProtoCommon.internal_static_HeartBeatRequest_descriptor;
      }

      public com.game.proto.ProtoCommon.HeartBeatRequest getDefaultInstanceForType() {
        return com.game.proto.ProtoCommon.HeartBeatRequest.getDefaultInstance();
      }

      public com.game.proto.ProtoCommon.HeartBeatRequest build() {
        com.game.proto.ProtoCommon.HeartBeatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.proto.ProtoCommon.HeartBeatRequest buildPartial() {
        com.game.proto.ProtoCommon.HeartBeatRequest result = new com.game.proto.ProtoCommon.HeartBeatRequest(this);
        result.clientTime_ = clientTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.proto.ProtoCommon.HeartBeatRequest) {
          return mergeFrom((com.game.proto.ProtoCommon.HeartBeatRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.proto.ProtoCommon.HeartBeatRequest other) {
        if (other == com.game.proto.ProtoCommon.HeartBeatRequest.getDefaultInstance()) return this;
        if (other.getClientTime() != 0L) {
          setClientTime(other.getClientTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.proto.ProtoCommon.HeartBeatRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.proto.ProtoCommon.HeartBeatRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long clientTime_ ;
      /**
       * <pre>
       * 客户端时间
       * </pre>
       *
       * <code>int64 clientTime = 1;</code>
       */
      public long getClientTime() {
        return clientTime_;
      }
      /**
       * <pre>
       * 客户端时间
       * </pre>
       *
       * <code>int64 clientTime = 1;</code>
       */
      public Builder setClientTime(long value) {
        
        clientTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端时间
       * </pre>
       *
       * <code>int64 clientTime = 1;</code>
       */
      public Builder clearClientTime() {
        
        clientTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:HeartBeatRequest)
    }

    // @@protoc_insertion_point(class_scope:HeartBeatRequest)
    private static final com.game.proto.ProtoCommon.HeartBeatRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.proto.ProtoCommon.HeartBeatRequest();
    }

    public static com.game.proto.ProtoCommon.HeartBeatRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatRequest>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatRequest>() {
      public HeartBeatRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeartBeatRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatRequest> getParserForType() {
      return PARSER;
    }

    public com.game.proto.ProtoCommon.HeartBeatRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 客户端时间
     * </pre>
     *
     * <code>int64 clientTime = 1;</code>
     */
    long getClientTime();

    /**
     * <pre>
     * 服务器时间
     * </pre>
     *
     * <code>int64 serverTime = 2;</code>
     */
    long getServerTime();
  }
  /**
   * Protobuf type {@code HeartBeatResponse}
   */
  public  static final class HeartBeatResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeatResponse)
      HeartBeatResponseOrBuilder {
    // Use HeartBeatResponse.newBuilder() to construct.
    private HeartBeatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatResponse() {
      clientTime_ = 0L;
      serverTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HeartBeatResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              clientTime_ = input.readInt64();
              break;
            }
            case 16: {

              serverTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.ProtoCommon.internal_static_HeartBeatResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.ProtoCommon.internal_static_HeartBeatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.ProtoCommon.HeartBeatResponse.class, com.game.proto.ProtoCommon.HeartBeatResponse.Builder.class);
    }

    public static final int CLIENTTIME_FIELD_NUMBER = 1;
    private long clientTime_;
    /**
     * <pre>
     * 客户端时间
     * </pre>
     *
     * <code>int64 clientTime = 1;</code>
     */
    public long getClientTime() {
      return clientTime_;
    }

    public static final int SERVERTIME_FIELD_NUMBER = 2;
    private long serverTime_;
    /**
     * <pre>
     * 服务器时间
     * </pre>
     *
     * <code>int64 serverTime = 2;</code>
     */
    public long getServerTime() {
      return serverTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientTime_ != 0L) {
        output.writeInt64(1, clientTime_);
      }
      if (serverTime_ != 0L) {
        output.writeInt64(2, serverTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientTime_);
      }
      if (serverTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, serverTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.proto.ProtoCommon.HeartBeatResponse)) {
        return super.equals(obj);
      }
      com.game.proto.ProtoCommon.HeartBeatResponse other = (com.game.proto.ProtoCommon.HeartBeatResponse) obj;

      boolean result = true;
      result = result && (getClientTime()
          == other.getClientTime());
      result = result && (getServerTime()
          == other.getServerTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getClientTime());
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.proto.ProtoCommon.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.ProtoCommon.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.HeartBeatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.ProtoCommon.HeartBeatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.HeartBeatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.proto.ProtoCommon.HeartBeatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.HeartBeatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.proto.ProtoCommon.HeartBeatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.proto.ProtoCommon.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.proto.ProtoCommon.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.proto.ProtoCommon.HeartBeatResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatResponse)
        com.game.proto.ProtoCommon.HeartBeatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.proto.ProtoCommon.internal_static_HeartBeatResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.proto.ProtoCommon.internal_static_HeartBeatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.proto.ProtoCommon.HeartBeatResponse.class, com.game.proto.ProtoCommon.HeartBeatResponse.Builder.class);
      }

      // Construct using com.game.proto.ProtoCommon.HeartBeatResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientTime_ = 0L;

        serverTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.proto.ProtoCommon.internal_static_HeartBeatResponse_descriptor;
      }

      public com.game.proto.ProtoCommon.HeartBeatResponse getDefaultInstanceForType() {
        return com.game.proto.ProtoCommon.HeartBeatResponse.getDefaultInstance();
      }

      public com.game.proto.ProtoCommon.HeartBeatResponse build() {
        com.game.proto.ProtoCommon.HeartBeatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.proto.ProtoCommon.HeartBeatResponse buildPartial() {
        com.game.proto.ProtoCommon.HeartBeatResponse result = new com.game.proto.ProtoCommon.HeartBeatResponse(this);
        result.clientTime_ = clientTime_;
        result.serverTime_ = serverTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.proto.ProtoCommon.HeartBeatResponse) {
          return mergeFrom((com.game.proto.ProtoCommon.HeartBeatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.proto.ProtoCommon.HeartBeatResponse other) {
        if (other == com.game.proto.ProtoCommon.HeartBeatResponse.getDefaultInstance()) return this;
        if (other.getClientTime() != 0L) {
          setClientTime(other.getClientTime());
        }
        if (other.getServerTime() != 0L) {
          setServerTime(other.getServerTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.proto.ProtoCommon.HeartBeatResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.proto.ProtoCommon.HeartBeatResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long clientTime_ ;
      /**
       * <pre>
       * 客户端时间
       * </pre>
       *
       * <code>int64 clientTime = 1;</code>
       */
      public long getClientTime() {
        return clientTime_;
      }
      /**
       * <pre>
       * 客户端时间
       * </pre>
       *
       * <code>int64 clientTime = 1;</code>
       */
      public Builder setClientTime(long value) {
        
        clientTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端时间
       * </pre>
       *
       * <code>int64 clientTime = 1;</code>
       */
      public Builder clearClientTime() {
        
        clientTime_ = 0L;
        onChanged();
        return this;
      }

      private long serverTime_ ;
      /**
       * <pre>
       * 服务器时间
       * </pre>
       *
       * <code>int64 serverTime = 2;</code>
       */
      public long getServerTime() {
        return serverTime_;
      }
      /**
       * <pre>
       * 服务器时间
       * </pre>
       *
       * <code>int64 serverTime = 2;</code>
       */
      public Builder setServerTime(long value) {
        
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器时间
       * </pre>
       *
       * <code>int64 serverTime = 2;</code>
       */
      public Builder clearServerTime() {
        
        serverTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:HeartBeatResponse)
    }

    // @@protoc_insertion_point(class_scope:HeartBeatResponse)
    private static final com.game.proto.ProtoCommon.HeartBeatResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.proto.ProtoCommon.HeartBeatResponse();
    }

    public static com.game.proto.ProtoCommon.HeartBeatResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatResponse>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatResponse>() {
      public HeartBeatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeartBeatResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatResponse> getParserForType() {
      return PARSER;
    }

    public com.game.proto.ProtoCommon.HeartBeatResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrorMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrorMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ProtoCommon.proto\"\037\n\014ErrorMessage\022\017\n\007e" +
      "rrCode\030\001 \001(\005\"&\n\020HeartBeatRequest\022\022\n\nclie" +
      "ntTime\030\001 \001(\003\";\n\021HeartBeatResponse\022\022\n\ncli" +
      "entTime\030\001 \001(\003\022\022\n\nserverTime\030\002 \001(\003*\263\001\n\nPr" +
      "otoError\022\013\n\007SUCCESS\020\000\022\n\n\006FAILED\020\001\022\027\n\023INV" +
      "ALID_LOGIN_TOKEN\020\002\022\027\n\023INVALID_GAME_TICKE" +
      "T\020\003\022\021\n\rINVALID_PARAM\020\n\022\027\n\023NAME_LENGTH_IN" +
      "VALID\020\013\022\031\n\025NOTICE_LENGTH_INVALID\020\014\022\023\n\017CO" +
      "ST_NOT_ENOUGH\020\r*\245\002\n\tProtoCode\022\013\n\007INVALID" +
      "\020\000\022\021\n\rERROR_MESSAGE\020\001\022\026\n\022HEART_BEAT_REQU",
      "EST\020\002\022\027\n\023HEART_BEAT_RESPONSE\020\003\022\021\n\rLOGIN_" +
      "REQUEST\020\n\022\022\n\016LOGIN_RESPONSE\020\013\022\022\n\016LOGOUT_" +
      "REQUEST\020\014\022\023\n\017LOGOUT_RESPONSE\020\r\022\024\n\020KICK_O" +
      "UT_REQUEST\020\016\022\025\n\021KICK_OUT_RESPONSE\020\017\022\026\n\022L" +
      "OGIN_INIT_REQUEST\020\024\022\030\n\024PERFORMANCE_TEST_" +
      "REQ\020\025\022\030\n\024PERFORMANCE_TEST_RES\020\026B\033\n\016com.g" +
      "ame.protoZ\t/protoGenb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ErrorMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ErrorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrorMessage_descriptor,
        new java.lang.String[] { "ErrCode", });
    internal_static_HeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatRequest_descriptor,
        new java.lang.String[] { "ClientTime", });
    internal_static_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatResponse_descriptor,
        new java.lang.String[] { "ClientTime", "ServerTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
