server:
  port: 8080
spring:
  application:
    name: router.V1
  cloud:
    config:
      enabled:  false
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
    allow-circular-references: true


discovery:
  endpoints:
   - http://localhost:2379
   - http://localhost:2379