spring:
  cloud:
    config:
      enabled:  false
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
    allow-circular-references: true

server:
  port: 8080

world-server:
  servers:
    - id: 100
      ip: 127.0.0.1
      port: 9081


