server:
  port: 8080
spring:
  application:
    name: game.V1
  cloud:
    config:
      enabled:  false
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
    allow-circular-references: true


#world-server:
#  servers:
#    - id: 100
#      ip: 127.0.0.1
#      port: 9081
#-------------------discovery ----------
discovery:
  endpoints:
    - http://localhost:2379
    - http://localhost:2379
  watch-servers:
    - service-name-prefix: world.V1
      areas:
        - area-id: 100
          connect: true

mongo:
  addrs: localhost:27017;localhost:27017
  userName: admin
  password: admin
